apiVersion: apps/v1
kind: Deployment
metadata:
  name: starscan-sub-deployment
  namespace: starcoin-main
  labels:
    app: starscan-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starscan-sub
  template:
    metadata:
      labels:
        app: starscan-sub
    spec:
      containers:
        - name: starscan-sub
          image: starcoin/starcoin_search:sha-0af24fa
          ports:
            - containerPort: 8600
          env:
            - name: HOSTS
              value: "main1.seed.starcoin.org,main2.seed.starcoin.org,main3.seed.starcoin.org,main4.seed.starcoin.org,main5.seed.starcoin.org,main6.seed.starcoin.org,main7.seed.starcoin.org,main8.seed.starcoin.org,main9.seed.starcoin.org"
            - name: NETWORK
              value: "main"
            - name: BG_TASK_JOBS
              value: "clean_pending_txn"
            - name: STARCOIN_ES_PWD
                valueFrom:
                  secretKeyRef:
                    name: elasticsearch-pw-elastic
                    key: password
            - name: STARCOIN_ES_URL
              value: "123.57.40.36"
            - name: STARCOIN_ES_PROTOCOL
              value: "http"
            - name: STARCOIN_ES_PORT
              value: "9200"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: SWAP_API_URL
              value: ""
            - name: SWAP_CONTRACT_ADDR
              value: ""
            - name: DS_URL
              value: ""
            - name: DB_USER_NAME
              value: ""
            - name: DB_PWD
              value: ""
            - name: PROGRAM_ARGS
              value: "subscribe"

