apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-indexer-stat-deployment
  namespace: starcoin-main
  labels:
    app: starcoin-indexer-stat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-indexer-stat
  template:
    metadata:
      labels:
        app: starcoin-indexer-stat
    spec:
      containers:
        - name: starcoin-indexer-stat
          image: starcoin/starcoin_indexer:sha-a66e9ab
          ports:
            - containerPort: 8300
          env:
            - name: HOSTS
              value: "main.seed.starcoin.org"
            - name: NETWORK
              value: "main.0727"
            - name: BG_TASK_JOBS
              value: "swap_stats"
            - name: TXN_OFFSET
              value: "0"
            - name: BULK_SIZE
              value: "100"
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw-elastic
                  key: password
            - name: STARCOIN_ES_URL
              value: "search-starcoin-es2-47avtmhexhbg7qtynzebcnnu64.ap-northeast-1.es.amazonaws.com"
            - name: STARCOIN_ES_PROTOCOL
              value: "https"
            - name: STARCOIN_ES_PORT
              value: "443"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: SWAP_API_URL
              value: "https://swap-api.starswap.xyz"
            - name: SWAP_CONTRACT_ADDR
              value: "0x8c109349c6bd91411d6bc962e080c4a3"
            - name: DS_URL
              value: "jdbc:postgresql://database-1.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com/starcoin"
            - name: DB_USER_NAME
              value: "starcoin"
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql-starcoin-yu
                  key: password
            - name: DB_SCHEMA
              value: "main"
            - name: PROGRAM_ARGS
              value: ""
