apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer-new-api-deployment
  labels:
    app: explorer-new-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-new-api
  template:
    metadata:
      labels:
        app: explorer-new-api
    spec:
      containers:
        - name: explorer-new-api
          image: starcoin/starcoin_scan:sha-5b6e308
          ports:
            - containerPort: 8500
          env:
            - name: STARCOIN_ES_URL
              value: "123.57.40.36"
            - name: STARCOIN_ES_PROTOCOL
              value: "http"
            - name: STARCOIN_ES_PORT
              value: "9200"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: STARCOIN_ES_INDEX_VERSION
              value:
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw-elastic
                  key: password
