apiVersion: v1
kind: Service
metadata:
  labels:
    app: explorer-new-api
  name: explorer-new-api
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8500
  selector:
    app: explorer-new-api
  type: LoadBalancer
status:
  loadBalancer: { }
